# Generated by Django 5.2.4 on 2025-09-30 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garage',
            name='is_parking_available',
            field=models.BooleanField(default=False),
        ),
    ]
