# Generated by Django 5.2.4 on 2025-09-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0002_alter_book_pubdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='adult',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.IntegerField(default=1),
        ),
    ]
