# Generated by Django 5.2.4 on 2025-09-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garages',
            name='closing_time',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='garages',
            name='opening_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
